config/routes.rb
Backlogger::Application.routes.draw do
  get '/auth/google_oauth2',          as: 'auth_google'
  get '/auth/google_oauth2/callback', to: 'sessions#google'
  get '/logout',                      to: 'sessions#destroy'

  resources :users do
    resources :backlogs do
      resources :backlog_sharings
      resources :stories

      member do
        get :cards
      end
    end
  end

  root to: 'main#index'
end

app/models/backlog.rb
class Backlog < ActiveRecord::Base
  serialize :story_order, Array

  has_many :stories
  belongs_to :user

  has_many :backlog_sharings
  has_many :shared_users, through: :backlog_sharings, source: :user

  before_save do
    self.story_order = ordered_stories.compact.map(&:id)
  end

  def ordered_stories
    story_index = stories.uncompleted.inject(Hash.new) {|h, s| h[s.id] = s; h}
    story_order.map{|id| story_index[id]}.compact
  end

  def total_complexity
    stories.uncompleted.sum(:story_points)
  end
end

app/models/backlog_sharing.rb
class BacklogSharing < ActiveRecord::Base

  belongs_to :user
  belongs_to :backlog

  validates :backlog_id, presence: true
  validates :user_id, presence: {message: 'cannot be found.'}
  validates :user_id, uniqueness: { scope: :backlog_id, message: 'has already been added.' }
  validate do
    if self.user_id == backlog.user_id
      errors.add(:user_id, 'is already the owner of the backlog.')
    end
  end

  def user_email= email
    self.user = User.where(email: email).first
  end

  def user_email
  end

end

app/models/story.rb
class Story < ActiveRecord::Base
  belongs_to :backlog, touch: true
  TABLE = self.arel_table


  scope :uncompleted,  ->{ where(TABLE[:compleated_at].eq(nil)) }
  scope :compleated,   ->{ where(TABLE[:compleated_at].not_eq(nil)) }

  validates :compleated_at, compleation: true

  def overview
    ["As a #{who}", "I want #{what}", "So that #{why}"].join(?\n)
  end

  def roi
    self.business_value.to_i / self.story_points.to_i
  rescue
    0
  end

  def compleated= val
    self.compleated_at = Time.now if val == true
  end

  def started= val
    self.started_at = Time.now if val == true
  end
end

app/models/user.rb
class User < ActiveRecord::Base

  has_many :backlogs

  has_many :backlog_sharings
  has_many :shared_backlogs, through: :backlog_sharings, source: :backlog

  def self.from_google_omniauth(auth_hash)
    self.find_or_initialize_by(google_uid: auth_hash[:uid]).tap do |user|
      user.first_name ||= auth_hash.info.first_name
      user.last_name  ||= auth_hash.info.last_name
      user.email      ||= auth_hash.info.email
      user.image        = auth_hash.info.image
      user.save!
    end
  end

  def name
    "#{self.first_name} #{self.last_name}"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_filter :require_user

  private
  def login(user)
    @current_user = user
    session[:user_id] = user.id
  end

  def logout
    @current_user = nil
    reset_session
    redirect_to root_url
  end

  def current_user
    @current_user ||= User.find(session[:user_id])
  rescue ActiveRecord::RecordNotFound
    nil
  end
  helper_method :current_user

  def require_user
    redirect_to auth_google_path unless current_user.present?
  end
end

app/controllers/backlog_sharings_controller.rb
class BacklogSharingsController < ApplicationController
  layout false
  respond_to :js

  def create
    @sharing = BacklogSharing.new(backlog_sharing_params)
    if can? :manage, @sharing.backlog
      @sharing.save!
    else
      # TODO: better error handling
      raise CanCan::AccessDenied.new("Not authorized!", :manage, @sharing.backlog)
    end
  rescue => e
    @exception = e
  end

  def backlog_sharing_params
    params.require(:backlog_sharing).permit(:user_email, :backlog_id)
  end
end

app/controllers/backlogs_controller.rb
class BacklogsController < ApplicationController
  layout false, only: [:cards, :update]

  def index
    @backlogs = current_user.backlogs + current_user.shared_backlogs
  end

  def show
    @backlog = Backlog.find(params[:id])
    if cannot?(:read, @backlog)
      flash[:danger] = 'you cannot access that backlog'
      redirect_to user_backlogs_path(current_user)
    end
  end

  def cards
    @stories = current_user.backlogs.find(params[:id]).stories.uncompleted
    @stories = @stories.where(id: params[:stories].split(?,).map(&:to_i)) if params[:stories]
  end

  def create
    backlog = current_user.backlogs.create(backlog_params)
    redirect_to [current_user, backlog]
  end

  def update
    backlog = Backlog.find(params[:id])
    authorize! :edit, backlog
    story_ids = params[:backlog][:story_order].split(',').map(&:to_i)
    backlog.story_order = story_ids
    backlog.save

  rescue CanCan::AccessDenied
    flash[:danger] = "Unable to update backlog"

  ensure
    respond_to do |format|
      format.html { redirect_to [current_user, backlog] }
      format.js
    end
  end

  private

  def backlog_params
    params.require(:backlog).permit(:name)
  end
end

app/controllers/main_controller.rb
class MainController < ApplicationController
  skip_before_filter :require_user, only: [:index]

  def index
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  skip_before_filter :require_user, only: [:google]

  def google
    user = User.from_google_omniauth(auth_hash)
    login(user)
    redirect_to user_backlogs_path(user)
  end

  def destroy
    logout
  end

  private
  def auth_hash
    request.env['omniauth.auth']
  end
end

app/controllers/stories_controller.rb
class StoriesController < ApplicationController
  def create
    story = backlog.stories.create(story_params)
    backlog.story_order << story.id
    backlog.save!
    redirect_to [current_user, backlog]
  end

  def update
    if can? :edit, backlog
      story = backlog.stories.find(params[:id])
      puts story_params.inspect
      story.update_attributes(story_params)
    else
      flash[:danger] = "no"
    end
    redirect_to [current_user, backlog]
  end

  def destroy
    story = backlog.stories.find(params[:id])
    backlog.story_order.delete story.id
    backlog.save
    story.destroy
    redirect_to [current_user, backlog]
  end


  private

  def backlog
    @backlog ||= Backlog.find(params[:backlog_id])
  end

  def story_params
    p = params.require('story').permit([:title, :who, :what, :why, :acceptance_criteria, :notes, :theme, :sprint_ready, :story_points, :business_value, :backlog_id, :created_at, :updated_at, :compleated, :started])
    p[:compleated] = p[:compleated] == 'true' if p[:compleated].present?
    p[:started] = p[:started] == 'true' if p[:started].present?
    p
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def hidden_class tf
    if tf
      'hidden'
    else
      ''
    end
  end

  def hidden_if true_or_false, id = nil
    content_tag :div, id: id, class: hidden_class(true_or_false) do
      yield
    end
  end

  def show_if true_or_false, id = nil
    hidden_if !true_or_false, id do
      yield
    end
  end
end

app/views/backlogs/_backlog_sharing.haml
%h4
  Shared with:

%ul#shared-users-list

  - @backlog.shared_users.each do |user|
    %li
      = "#{user.name} (#{user.email})"



%h4
  Add Shared Users:
= form_for [@backlog.user, @backlog, BacklogSharing.new(backlog: @backlog)], remote: true do |f|
  = f.hidden_field :backlog_id
  = f.text_field   :user_email
  = f.submit "Add User", class: 'btn btn-primary btn-xs'

app/views/backlogs/_stories_list.haml
.row
  .col-md-12
    %table.table.table-striped.sorted-table.story-table
      %thead
        %tr
          %th.grabber
          %th.id                 id
          %th.title              title
          %th.overview           overview
          %th.points.text-center points
          %th.roi.text-center    roi
          %th.actions
      %tbody
        - stories.each do |story|
          = cache [backlog, story, 'story-row'] do
            %tr{'data-story-id' => story.id}
              %td.grabber |||

              %td
                = story.id


              %td{"data-target" => "#edit-story-#{story.id}", "data-toggle" => "modal"}
                %strong
                  = story.title

              %td{"data-target" => "#edit-story-#{story.id}", "data-toggle" => "modal"}
                - story.overview.split("\n").each do |line|
                  %p= line

              %td.text-center
                = story.story_points

              %td.text-center
                = story.roi

              %td
                .pull-right
                  .btn-group.btn-group-xs
                    %button.btn.btn-default.dropdown-toggle{"data-toggle" => "dropdown", type: "button"}
                      Actions
                      %span.caret
                    %ul.dropdown-menu
                      %li
                        - field, text = story.started_at.present? ? [:compleated, 'compleated'] : [:started, 'start']
                        - form_name = "edit_story_#{text}_#{story.id}"
                        - js = "$('##{form_name}').submit();"
                        = form_for [current_user, backlog, story], html: {  role: "form", id: form_name } do |f|
                          = f.hidden_field field, value: true
                        %a{onclick: js}
                          = text
                      %li
                        %a{"data-target" => "#duplicate-story-#{story.id}", "data-toggle" => "modal"}
                          duplicate
                      %li
                        = link_to 'remove', [current_user, backlog, story], method: :delete

                .clearfix{ style: 'margin-bottom: 1em;'}
                .pull-right
                  - if story.started_at.present?
                    %span.label.label-success started
                  - elsif story.sprint_ready
                    %span.label.label-info sprint ready
                  - else
                    %span.label.label-danger needs review





              = render 'stories/form_modal', id: "edit-story-#{story.id}", backlog: backlog, story: story
              = render 'stories/form_modal', id: "duplicate-story-#{story.id}", backlog: backlog, story: story.dup

app/views/backlogs/cards.haml
!!! 5
%html(lang="en")
  %head
    %meta(charset="utf-8")
    %meta(http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1")
    %meta(name="viewport" content="width=device-width, initial-scale=1.0")
    %title= content_for?(:title) ? yield(:title) : "backlogger"
    = csrf_meta_tags

    / Le HTML5 shim, for IE6-8 support of HTML elements
    /[if lt IE 9]
      = javascript_include_tag "http://html5shim.googlecode.com/svn/trunk/html5.js"
    = stylesheet_link_tag "application", :media => "all"
    = yield(:page_stylesheet) if content_for?(:page_stylesheet)


  %body.story-cards
    - @stories.each_slice(2).each_with_index do |story_row, idx|
      - story_row.each do |story|
        = render 'stories/card', story: story
      - if (idx + 1) % 3 == 0
        .page-break


    = javascript_include_tag "application"
    = yield(:page_javascript) if content_for?(:page_javascript)

app/views/backlogs/index.haml
%br
.container
  .row
    .col-md-10
      %ol
        - @backlogs.each do |backlog|
          %li
            %h2
              %a{href: user_backlog_path(backlog.user, backlog)}
                = backlog.name

    .col-md-2
      %a.btn.btn-info.btn-sm{"data-target" => "#new-backlog", "data-toggle" => "modal"}
        Create Backlog

/ Modal
#new-backlog.modal.fade{role: "dialog", tabindex: "-1"}
  .modal-dialog
    .modal-content
      = form_for [current_user, Backlog.new], html: { role: "form" } do |f|
        .modal-header
          %button.close{"aria-hidden" => "true", "data-dismiss" => "modal", type: "button"} &#215;
          %h2
            New Backlog


        .modal-body.form-horizontal
          .form-group
            = f.label :name, class: 'col-sm-2 control-label'
            .col-sm-10
              = f.text_field :name, class: 'form-control', placeholder: "backlog name"

        .modal-footer
          %button.btn.btn-default{"data-dismiss" => "modal", type: "button"} Close
          = f.submit 'Create', class: 'btn btn-primary'

app/views/backlogs/show.haml
= cache [current_user, @backlog, 'show'] do
  .row
    .col-lg-12
      .bottom-right
        %ul.nav.nav-pills
          %li.active
            %a{"data-toggle" => "tab", href: "#ordered-stories"} Stories
          %li
            %a{"data-toggle" => "tab", href: "#dashboard"} Dashboard
          - if can? :edit, @backlog
            %li
              %a{"data-toggle" => "tab", href: "#sharing"} Sharing
            %li
              %a{"data-toggle" => "tab", href: "#settings"} Settings
      %h1
        = @backlog.name
        %span.badge.total-complexity{'data-toggle' => "tooltip", 'data-placement' => "bottom", 'title' => "Remaining Complexity"}
          = @backlog.total_complexity





  .tab-content
    #ordered-stories.tab-pane.active
      = render 'stories_list', backlog: @backlog, stories: @backlog.ordered_stories
      .row
        .col-lg-12
          .pull-right
            %a.btn.btn-info.btn-sm{"data-target" => "#new-story", "data-toggle" => "modal"}
              Add Story
            %a.btn.btn-info.btn-sm{href: cards_user_backlog_path(current_user, @backlog)}
              Print Cards
          = render 'stories/form_modal', id: "new-story", backlog: @backlog, story: Story.new

    #dashboard.tab-pane
      Dashboard

    - if can? :edit, @backlog
      #sharing.tab-pane
        = render 'backlog_sharing', backlog: @backlog

      #settings.tab-pane
        settings


  .hidden
    = form_for [current_user, @backlog], html: {id: 'backlog_form'}, remote: true do |f|
      = f.hidden_field :story_order

app/views/layouts/_header.haml
.navbar.navbar-default
  .navbar-header
    %button.navbar-toggle{"data-target" => ".navbar-responsive-collapse", "data-toggle" => "collapse", type: "button"}
      %span.icon-bar
      %span.icon-bar
      %span.icon-bar
    %a.navbar-brand{href: root_path} Backlogger
  .navbar-collapse.collapse.navbar-responsive-collapse

    %ul.nav.navbar-nav.navbar-right
      - if current_user.present?
        %li.dropdown
          %a.dropdown-toggle{"data-toggle" => "dropdown", href: "#"}
            = "#{current_user.first_name} #{current_user.last_name}"
            %b.caret
          %ul.dropdown-menu
            %li
              %a{href: user_backlogs_path(current_user)} My Backlogs
            %li.divider
            %li
              %a{href: auth_google_path}
                Switch Account
            %li
              %a{href: logout_path} Sign Out
      - else
        %li
          %a{href: auth_google_path}
            Login with Google

app/views/layouts/application.haml
!!! 5
%html(lang="en")
  %head
    %meta(charset="utf-8")
    %meta(http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1")
    %meta(name="viewport" content="width=device-width, initial-scale=1.0")
    %title= content_for?(:title) ? yield(:title) : "backlogger"
    = csrf_meta_tags
    / Le HTML5 shim, for IE6-8 support of HTML elements
    /[if lt IE 9]
      = javascript_include_tag "http://html5shim.googlecode.com/svn/trunk/html5.js"
    = stylesheet_link_tag "application", :media => "all"
    = yield(:page_stylesheet) if content_for?(:page_stylesheet)


  %body
    .container
      = render 'layouts/header'

      = yield

    .alerts
      - flash.each do |key, message|
        .alert{class: "alert-#{key}"}
          %button{'type' => "button", 'class' => 'close', 'data-dismiss' => "alert", 'aria-hidden' => "true"} &times;
          = message

    /
      Javascripts
      \==================================================
    / Placed at the end of the document so the pages load faster
    = javascript_include_tag "application"
    = yield(:page_javascript) if content_for?(:page_javascript)

app/views/main/index.haml
%h2
  Hello World

app/views/stories/_card.haml
.story-card
  .id
    %h4
      %strong
        = story.backlog.name.split.map(&:first).join.upcase + story.id.to_s

  .qr-code
    - data = URI::encode "#{user_backlog_story_url(current_user, story.backlog, story)}"
    %img{src: "https://api.qrserver.com/v1/create-qr-code/?size=50x50&data=#{data}"}
  .clearfix
  .title.text-center
    %h2= story.title.first(40)

  .overview.text-center
    = story.overview.gsub(/\n/, ', ')

  .points.text-center
    .col-xs-4
      %h4
        Points:
      = story.story_points || '---'

    .col-xs-4
      %h4
        Value:
      = story.business_value || '---'

    .col-xs-4
      %h4
        ROI:
      = story.roi || '---'

app/views/stories/_form_modal.haml
/ Modal
.modal.fade{id: id, role: "dialog", tabindex: "-1"}
  .modal-dialog
    .modal-content
      = form_for [current_user, backlog, story], html: {  role: "form" } do |f|
        .modal-header
          %button.close{"aria-hidden" => "true", "data-dismiss" => "modal", type: "button"} &#215;
          .form-group
            = f.text_field :title, class: 'form-control', placeholder: "Story title"

          %label
            = f.check_box :sprint_ready
            sprint ready

        .modal-body.form-horizontal
          .form-group
            = f.label :theme, class: 'col-sm-2 control-label'
            .col-sm-10
              = f.text_field :theme, class: 'form-control', placeholder: "theme"

          .form-group
            = f.label :who, "As a", class: 'col-sm-2 control-label'
            .col-sm-10
              = f.text_field :who, class: 'form-control', placeholder: "user role"

          .form-group
            = f.label :who, "I want", class: 'col-sm-2 control-label'
            .col-sm-10
              = f.text_field :what, class: 'form-control', placeholder: "something"

          .form-group
            = f.label :why, "So that", class: 'col-sm-2 control-label'
            .col-sm-10
              = f.text_field :why, class: 'form-control', placeholder: "i get value"

          .form-group
            = f.label :acceptance_criteria, class: 'col-sm-2 control-label'
            .col-sm-10
              = f.text_area :acceptance_criteria, class: 'form-control', placeholder: "- pass fail acceptance criteria"

          .form-group
            = f.label :notes, class: 'col-sm-2 control-label'
            .col-sm-10
              = f.text_area :notes, class: 'form-control', placeholder: "- pass fail acceptance criteria"

          .form-group
            = f.label :story_points, class: 'col-sm-2 control-label'
            .col-sm-2
              = f.text_field :story_points, class: 'form-control', placeholder: "1,2,3,..."

          .form-group
            = f.label :business_value, class: 'col-sm-2 control-label'
            .col-sm-4
              = f.text_field :business_value, class: 'form-control', placeholder: "1000,2000,3000,..."




        .modal-footer
          %button.btn.btn-default{"data-dismiss" => "modal", type: "button"} Close
          = f.submit 'Save changes', class: 'btn btn-primary'